### ISSUE TITLE
Check for `err`

### ISSUE THREAD

**Issue by chrisjhoughton** [sauce/customerio#2]
See https://github.com/sauce/customerio/pull/1#issuecomment-81827903.

**Comment by liviubunda** [comment]
+1 

Using the module to sync some data for transactional emails. 

I do get an error that something went wrong, but it would be nice to know exactly what. For example, by studying your code and the needle module, my problem could be:
- network error
- timeout error
- certificate error [unlikely]

Here is the stack trace:

TypeError: Cannot read property 'statusCode' of undefined 
at /usr/code/node_modules/node-customerio/lib/customerio.js:73:21 
at done (/usr/code/node_modules/node-customerio/node_modules/needle/lib/needle.js:234:9) 
at ClientRequest.<anonymous> (/usr/code/node_modules/node-customerio/node_modules/needle/lib/needle.js:381:7) 
at ClientRequest.emit (events.js:95:17) 
at CleartextStream.socketCloseListener (http.js:1527:9) 
at CleartextStream.emit (events.js:117:20) 
at tls.js:694:10 
at /usr/code/node_modules/newrelic/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:188:31 
at /usr/code/node_modules/newrelic/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:188:31 
at process._tickDomainCallback (node.js:486:13)

**Comment by liviubunda** [comment]
Thanks!
